manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: pierrechevalier83
      revision: rosa
      import: app/west.yml
  self:
    path: config
