manifest:
  remotes:
    - name: pierrechevalier83
      url-base: https://github.com/pierrechevalier83
  projects:
    - name: zmk
      remote: pierrechevalier83
      revision: rosa
      import: app/west.yml
  self:
    path: config
